import { AVATAR_OWL, AVATAR_BIRDIE, AVATAR_WILD_LIFE2, AVATAR_GOOSE, AVATAR_WILD_LIFE, AVATAR_BIRDIE2 } from 'Constants/iconNames';

export const avatars = [ AVATAR_BIRDIE, AVATAR_OWL, AVATAR_GOOSE, AVATAR_WILD_LIFE2, AVATAR_BIRDIE2, AVATAR_WILD_LIFE, ];